version: "3.8"
services:
  app:
    container_name: shairu-website-dev-frontend
    image: shairu-website-dev
    environment:
     #add project level env variables
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000